version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - Andyterrify
  - tommitchelmore
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.12.0
    - 5.12.5
  - dependency-name: nanoid
    versions:
    - 3.1.21
