# require extension https://marketplace.visualstudio.com/items?itemName=42Crunch.vscode-openapi

openapi: "3.0.2"
info:
  title: Another ShareX Server
  version: "1.0"
servers:
  - url: https://localhost:3000/
paths:
  /auth/register:
    post:
      tags:
        - "auth"
      description: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username: 
                  type: string
                password:
                  type: string
                displayName:
                  type: string
                email:
                  type: string

      responses:
        "201":
          description: User created successfully
        "400":
          description: Not enough data provided
        "409":
          description: User already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                example:
                  error: An account with that field 'username' already exists.
