# require extension https://marketplace.visualstudio.com/items?itemName=42Crunch.vscode-openapi

openapi: "3.0.2"
info:
  title: Another ShareX Server
  version: "1.0"
servers:
  - url: https://localhost:3000/
paths:
  /auth/register:
    post:
      tags:
        - "auth"
      description: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
        "400":
          description: Not enough data provided by client
          content:
            application/json:
              schema:
                properties:
                  error:
                    type: string
                    example: "Missing field 'username'"
        "409":
          description: Account with provided data is already registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: An account with fild 'jeff5234' already exists

components:
  schemas:
    User:
      properties:
        id:
          type: string
          uniqueItems: true
          readOnly: true
        username:
          type: string
          minLength: 1
          example: "jeff5234"
        displayName:
          type: string
          minLength: 1
          example: "Jeff Winger"
        password:
          type: string
          minLength: 1
        email:
          type: string
          format: email
          example: "jeff@example.com"
        accountCreated:
          type: string
          format: date-time
          readOnly: true
          example: "2017-07-21T17:32:28Z"
        access:
          type: string
          enum:
            - admin
            - basic
          default: basic
          readOnly: true
      required:
        - username
        - displayName
        - password
